using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Hal65_69
{
    class Program
    {
        static void Main(string[] args)
        {
            String NAMA, KLS, NPM, SKS;
            Int32 AMPuts, AMPuas, AMPtugas, AMPhdr, NAAMP;
            Int32 MTKuts, MTKuas, MTKtugas, MTKhdr, NAMTK;
            Int32 MATLANuts, MATLANuas, MATLANtugas, MATLANhdr, NAMATLAN;
            Int32 LMuts, LMuas, LMtugas, LMhdr, NALM;
            Int32 PLMuts, PLMuas, PLMtugas, PLMhdr, NAPLM;
            Int32 PKNuts, PKNuas, PKNtugas, PKNhdr, NAPKN;
            Int32 PTIuts, PTIuas, PTItugas, PTIhdr, NAPTI;
            Int32 BInuts, BInuas, BIntugas, BInhdr, NABIn;
            Int32 TPuts, TPuas, TPtugas, TPhdr, NATP;
            Int32 APuts, APuas, APtugas, APhdr, NAAP;
            Int32 PAPuts, PAPuas, PAPtugas, PAPhdr, NAPAP;
            Console.WriteLine("                 TRANSKIP NILAI AKADEMIK                 ");
            Console.WriteLine("=========================================================");
            Console.Write("     Inputkan Nama Anda      :  ");
            NAMA = Console.ReadLine();
            Console.Write("     Inputkan Kelas Anda     :  ");
            KLS = Console.ReadLine();
            Console.Write("     Inputkan NPM Anda       :  ");
            NPM = Console.ReadLine();
            Console.Write("     Inputkan Jumlah SKS Anda:  ");
            SKS = Console.ReadLine();
            Console.WriteLine("     Berikut Terlampir Nama Mata Kuliah:  ");
            Console.WriteLine("\n\tAplikasi Manajemen Perkantoran");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            AMPuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            AMPuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            AMPtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            AMPhdr = Convert.ToInt32(Console.ReadLine());
            NAAMP = (AMPuts + AMPuas + AMPtugas + AMPhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Aplikasi Manajemen Perkantoran: " + NAAMP);
            Console.WriteLine("\n\tMatematika Teknologi Informasi I");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            MTKuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            MTKuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            MTKtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            MTKhdr = Convert.ToInt32(Console.ReadLine());
            NAMTK = (MTKuts + MTKuas + MTKtugas + MTKhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Matematika Teknologi Informasi I: " + NAMTK);
            Console.WriteLine("\n\tMatematika Lanjut I");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            MATLANuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            MATLANuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            MATLANtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            MATLANhdr = Convert.ToInt32(Console.ReadLine());
            NAMATLAN = (MATLANuts + MATLANuas + MATLANtugas + MATLANhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Matematika Lanjut I: " + NAMATLAN);
            Console.WriteLine("\n\tListrik dan Magnet");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            LMuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            LMuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            LMtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            LMhdr = Convert.ToInt32(Console.ReadLine());
            NALM = (LMuts + LMuas + LMtugas + LMhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Listrik dan Magnet: " + NALM);
            Console.WriteLine("\n\tPraktikum Listrik dan Magnet");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            PLMuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            PLMuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            PLMtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            PLMhdr = Convert.ToInt32(Console.ReadLine());
            NAPLM = (PLMuts + PLMuas + PLMtugas + PLMhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Praktikum Listrik dan Magnet: " + NAPLM);
            Console.WriteLine("\n\tPendidikan Kewarganegaraan");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            PKNuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            PKNuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            PKNtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            PKNhdr = Convert.ToInt32(Console.ReadLine());
            NAPKN = (PKNuts + PKNuas + PKNtugas + PKNhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Pendidikan Kewarganegaraan: " + NAPKN);
            Console.WriteLine("\n\tPengantar Teknologi Komunikasi dan Informasi");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            PTIuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            PTIuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            PTItugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            PTIhdr = Convert.ToInt32(Console.ReadLine());
            NAPTI = (PTIuts + PTIuas + PTItugas + PTIhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Pengantar Teknologi Komunikasi dan Informasi: " + NAPTI);
            Console.WriteLine("\n\tPengantar Bahasa Indonesia");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            BInuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            BInuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            BIntugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            BInhdr = Convert.ToInt32(Console.ReadLine());
            NABIn = (BInuts + BInuas + BIntugas + BInhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Bahasa Indonesia:  " + NABIn);
            Console.WriteLine("\n\tPraktikum Algoritma dan Pemrograman I");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            PAPuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            PAPuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            PAPtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            PAPhdr = Convert.ToInt32(Console.ReadLine());
            NAPAP = (PAPuts + PAPuas + PAPtugas + PAPhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Praktikum Algoritma dan Pemrograman I: " + NAPAP);
            Console.WriteLine("\n\tTOEFL Preparation I");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            TPuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            TPuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            TPtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            TPhdr = Convert.ToInt32(Console.ReadLine());
            NATP = (TPuts + TPuas + TPtugas + TPhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah TOEFL Preparation I: " + NATP);
            Console.WriteLine("\n\tAlgoritma dan Pemrograman Informatika I");
            Console.Write("\t\t Inputkan Nilai UTS      :  ");
            APuts = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai UAS      :  ");
            APuas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Tugas    :  ");
            APtugas = Convert.ToInt32(Console.ReadLine());
            Console.Write("\t\t Inputkan Nilai Kehadiran:  ");
            APhdr = Convert.ToInt32(Console.ReadLine());
            NAAP = (APuts + APuas + APtugas + APhdr) / 4;
            Console.WriteLine("\tNilai Akhir Mata Kuliah Alg & Pem.I: " + NAAP);
            Console.WriteLine("=================================================================");
            Console.WriteLine(" | REKAPITULASI NILAI AKHIR DARI SEMUA MATA KULIAH SEMESTER I |  ");
            Console.WriteLine("=================================================================");
            Console.WriteLine("Nilai Akhir Mata Kuliah Aplikasi Manajemen Perkantoran Adalah              : " + NAAMP);
            Console.WriteLine("Nilai Akhir Mata Kuliah Matematika Teknologi Informasi Adalah              : " + NAMTK);
            Console.WriteLine("Nilai Akhir Mata Kuliah Matematika Lanjut Adalah                           : " + NAMATLAN);
            Console.WriteLine("Nilai Akhir Mata Kuliah Pengantar Teknologi Komunikasi dan Informasi Adalah: " + NAPTI);
            Console.WriteLine("Nilai Akhir Mata Kuliah Listrik dan Magnet Adalah                          : " + NALM);
            Console.WriteLine("Nilai Akhir Mata Kuliah Praktikum Listrik dan Magnet Adalah                : " + NAPLM);
            Console.WriteLine("Nilai Akhir Mata Kuliah Bahasa Indonesia Adalah                            : " + NABIn);
            Console.WriteLine("Nilai Akhir Mata Kuliah B.Inggris TOEFL Preparation Adalah                 : " + NATP);
            Console.WriteLine("Nilai Akhir Mata Kuliah Algoritma dan Pemrograman I Adalah                 : " + NAAP);
            Console.WriteLine("Nilai Akhir Mata Kuliah Praktikum Algoritma dan Pemrograman I Adalah       : " + NAPAP);
            Console.WriteLine("=============================================================");

        }
    }
}